version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch  -Ediscovery.type=single-node
    networks:
      - elk_network
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: kibana
    image: kibana:7.3.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - elk_network

  # logstash_csv:
  #   container_name: logstash_csv
  #   image: logstash:7.3.0
  #   command: logstash -f /var/opt/logstash-conf/csv/logstash.conf
  #   ports:
  #     - '5044:5044'
  #   volumes:
  #     - ./logstash/csv/:/var/opt/logstash-conf/csv   
  #   depends_on:
  #     - elasticsearch
  #   restart: always
  #   networks:
  #     - elk_network
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1

  logstash_twitter:
    container_name: logstash_twitter
    image: logstash:7.3.0
    command: logstash -f /var/opt/logstash-conf/twitter/logstash.conf
    ports:
      - '5045:5044'
    volumes:
      - ./logstash/twitter:/var/opt/logstash-conf/twitter
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - elk_network
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  logstash_twitter:
  # logstash_csv:
  
networks:
  elk_network:
    driver: bridge